version: '3'

services:
  nfs-server:
    build: .
    container_name: nfs-server
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SETPCAP
      - SYS_RESOURCE
    ports:
      - "2050:2049"
      - "5111:111/udp"
    volumes:
      - '/mnt:/mnt'
      - './exports:/etc/exports'
    networks:
      - nfs-network

networks:
  nfs-network:
    driver: bridge