kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  podSubnet: "172.25.1.0/24"
  serviceSubnet: "172.25.2.0/24"
  disableDefaultCNI: true

nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 6443
    hostPort: 6443
    protocol: TCP
- role: worker
- role: worker
