apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod-1
spec:
  containers:
    - name: app
      image: busybox
      command: ["/bin/bash", "-c", "while true; echo $(date) >> /mnt/data/log.txt; sleep 5;done"]
      resources:
        limits:
          cpu: "0.5"
          memory: "256Mi"
        requests:
          cpu: "0.2"
          memory: "128Mi"
      volumeMounts:
        - mountPath: /mnt/data
          name: nfs-storage
  volumes:
    - name: nfs-storage
      persistentVolumeClaim:
        claimName: nfs-pvc
---
apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod-2
spec:
  containers:
    - name: app
      image: busybox
      command: ["/bin/bash", "-c", "while true; echo $(date) >> /mnt/data/log.txt; sleep 5;done"]
      resources:
        limits:
          cpu: "0.5"
          memory: "256Mi"
        requests:
          cpu: "0.2"
          memory: "128Mi"
      volumeMounts:
        - mountPath: /mnt/data
          name: nfs-storage
  volumes:
    - name: nfs-storage
      persistentVolumeClaim:
        claimName: nfs-pvc
---
apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod-3
spec:
  containers:
    - name: app
      image: busybox
      command: ["/bin/bash", "-c", "while true; echo $(date) >> /mnt/data/log.txt; sleep 5;done"]
      resources:
        limits:
          cpu: "0.5"
          memory: "256Mi"
        requests:
          cpu: "0.2"
          memory: "128Mi"
      volumeMounts:
        - mountPath: /mnt/data
          name: nfs-storage
  volumes:
    - name: nfs-storage
      persistentVolumeClaim:
        claimName: nfs-pvc
---
