apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-app
  template:
    metadata:
      labels:
        app: nfs-app
    spec:
      containers:
      - name: nfs-container
        image: your-nfs-server-image:latest # Ensure git_log.sh is added to this image
        command: [ "/bin/sh", "-c", "crond -f -d 8" ] # Start cron in the foreground with logging
        volumeMounts:
        - mountPath: /mnt
          name: nfs-storage
        - mountPath: /logs
          name: logs-dir
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"

      volumes:
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: nfs-pvc
      - name: logs-dir
        hostPath:
          path: ~/nfs-server/logs # Ensure the path is accessible on the host
          type: DirectoryOrCreate
