apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-app
  template:
    metadata:
      labels:
        app: nfs-app
    spec:
      containers:
      - name: nfs-client
        image: alpine:latest
        command: [ "/bin/sh", "-c", "sh /mnt/scripts/client-logger.sh" ]
        volumeMounts:
        - mountPath: /mnt
          name: nfs-mount
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1"
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      volumes:
      - name: nfs-mount
        persistentVolumeClaim:
          claimName: nfs-pvc
