apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-deployment
spec:
  replicas: 3 # Number of pod replicas you want
  selector:
    matchLabels:
      app: nfs-app
  template:
    metadata:
      labels:
        app: nfs-app
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: app
        image: alpine:latest
        command: [ "/bin/sh", "-c", "tail -f /dev/null" ]
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.1"
            memory: "64Mi"
        volumeMounts:
        - mountPath: /mnt
          name: nfs-storage

      - name: filebeat-sidecar
        image: docker.elastic.co/beats/filebeat:7.17.5
        env:
        - name: FLUENTD_HOST
          value: "172.25.0.4"
        volumeMounts:
        - name: nfs-storage
          mountPath: /var/log/nfs-app
        - name: config
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
        args: [ "-c", "/usr/share/filebeat/filebeat.yml" ]
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.1"
            memory: "64Mi"

      volumes:
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: nfs-pvc
      - name: config
        configMap:
          name: filebeat-config
