apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nfs-app
  template:
    metadata:
      labels:
        app: nfs-app
    spec:
      containers:
      - name: nfs-container
        image: arm64v8/busybox:latest
        command: [ "/bin/sh", "-c", "while true; do /usr/local/bin/log-client-login.sh; sleep 10; done" ]
        volumeMounts:
        - mountPath: /mnt
          name: nfs-storage
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

      volumes:
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: nfs-pvc
