apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-app
  template:
    metadata:
      labels:
        app: nfs-app
    spec:
      containers:
      - name: nfs-client
        image: busybox # Using busybox as a lightweight image
        command: [ "/bin/sh", "-c", "while true; do echo \"$(date): Client $(hostname) logged in\" >> /mnt/logs/login.txt; sleep 60; done" ]
        volumeMounts:
        - mountPath: /mnt
          name: nfs-storage
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
      volumes:
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: nfs-pvc
