apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-deployment
spec:
  replicas: 3 # Number of pod replicas you want
  selector:
    matchLabels:
      app: nfs-app
  template:
    metadata:
      labels:
        app: nfs-app
    spec:
      containers:
      - name: app
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
        - 
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.1"
            memory: "64Mi"
        volumeMounts:
        - name: nfs-storage
          mountPath: /mnt
      volumes:
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: nfs-pvc
