apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  nfs:
    path: /mnt
    server: 127.0.0.1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
