apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt
    server: 172.20.0.2
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""